#pragma once
#include "util/Joaat.hpp"
#include "CategoryUtils.hpp"

namespace YimMenu
{
	struct ObjectModelDefinition : public ModelDefinition
	{
	};

	inline std::vector<std::pair<const char*, std::vector<ObjectModelDefinition>>> g_ObjectCategories = 
	{
		{"Fences", {
			{"p_chickenfence01x"_J, "Chicken Fence"},
			{"p_chickenfence03x"_J, "Chicken Fence 2"},
			{"p_chickenfencepost"_J, "Chicken Fence Post"},
			{"p_app_stablefence01ax"_J, "Stable Fence"},
			{"p_app_stablefence01x"_J, "Stable Fence 2"},
			{"p_app_stablefence04x"_J, "Stable Fence 3"},
			{"p_app_stablefence06x"_J, "Stable Fence Post"},
		}},
		{"Signs", {
			{"p_sign01x"_J, "Posters 1"},
			{"p_sign03x"_J, "Posters 2"},
			{"p_sign05x"_J, "Posters 3"},
			{"p_sign_church01x"_J, "Church Sign"},
			{"p_signdoctorrho_a"_J, "Doctor Sign 1"},
			{"p_signdoctorrho_b"_J, "Doctor Sign 2"},
			{"p_sign_miners01x"_J, "Union Sign 1"},
			{"p_sign_miners02x"_J, "Union Sign 2"},
			{"p_sign_miners03x"_J, "Union Sign 3"},
			{"p_sign_miners04x"_J, "Union Sign 4"},
			{"p_signmorgrho_a"_J, "Morgue Sign"},
			{"p_sign_roomsval_a"_J, "Hotel Sign 1"},
			{"p_valhotelsign_01x"_J, "Hotel Sign 2"},
			{"p_sign_suffragette01x"_J, "Suffragette Sign 1"},
			{"p_sign_suffragette02x"_J, "Suffragette Sign 2"},
			{"p_sign_suffragette03x"_J, "Suffragette Sign 3"},
			{"p_sign_suffragette04x"_J, "Suffragette Sign 4"},
			{"p_sign_suffragette05x"_J, "Suffragette Sign 5"},
			{"p_sign_protestwag01x"_J, "Suffragette Sign 6"},
			{"p_sandwichboardwomen01x"_J, "Suffragette Sign 7"},
			{"p_valsmithsign01x"_J, "Blacksmith Sign"},
			{"p_sandwichboard01x"_J, "Market Sign"},
			{"p_sandwichboard02x"_J, "Now Open Sign"},
			{"p_sandwichboard03x"_J, "Hats Sign"}, // idk what to call this one
			{"p_sandwichboard05x"_J, "Lager Sign"},
			{"p_sandwichboard07x"_J, "Menu Sign"},
			{"p_sandwichboard08x"_J, "Eugenics Sign"},
			{"p_sandwichboard09x"_J, "Cult Sign"},
			{"p_helpwantedsign01x"_J, "Help Wanted"},
			{"p_sca_lemoynebordersign"_J, "Lemoyne Sign"},
			{"p_sca_westelizabeth_sign"_J, "West Elizabeth Sign"},
			{"rho_tsign_01"_J, "Rhodes Sign"},
		}},
		{"Racetracks", { // TODO: no work?
			{"mp001_p_mp_track_joint01"_J, "Joint 1"},
			{"mp001_p_mp_track_joint02"_J, "Joint 2"},
			{"mp001_p_mp_track_joint03"_J, "Joint 3"},
			{"mp001_p_mp_track_joint04"_J, "Joint 4"},
			{"mp001_p_mp_track_leftturn01"_J, "Left Turn 1"},
			{"mp001_p_mp_track_leftturn02"_J, "Left Turn 2"},
			{"mp001_p_mp_track_leftturn03"_J, "Left Turn 3"},
			{"mp001_p_mp_track_leftturn04"_J, "Left Turn 4"},
			{"mp001_p_mp_track_narrow01"_J, "Narrow 1"},
			{"mp001_p_mp_track_narrow02"_J, "Narrow 2"},
			{"mp001_p_mp_track_narrow03"_J, "Narrow 3"},
			{"mp001_p_mp_track_narrow04"_J, "Narrow 4"},
			{"mp001_p_mp_track_narrowjoint01"_J, "Narrow Joint 1"},
			{"mp001_p_mp_track_narrowjoint02"_J, "Narrow Joint 2"},
			{"mp001_p_mp_track_narrowjoint03"_J, "Narrow Joint 3"},
			{"mp001_p_mp_track_narrowjoint04"_J, "Narrow Joint 4"},
			{"mp001_p_mp_track_rightturn01"_J, "Right Turn 1"},
			{"mp001_p_mp_track_rightturn02"_J, "Right Turn 2"},
			{"mp001_p_mp_track_rightturn03"_J, "Right Turn 3"},
			{"mp001_p_mp_track_rightturn04"_J, "Right Turn 4"},
			{"mp001_p_mp_track_shaped01"_J, "Shaped 1"},
			{"mp001_p_mp_track_shaped02"_J, "Shaped 2"},
			{"mp001_p_mp_track_shaped03"_J, "Shaped 3"},
			{"mp001_p_mp_track_shaped04"_J, "Shaped 4"},
			{"mp001_p_mp_track_straight01"_J, "Straight 1"},
			{"mp001_p_mp_track_straight02"_J, "Straight 2"},
			{"mp001_p_mp_track_straight03"_J, "Straight 3"},
			{"mp001_p_mp_track_straight04"_J, "Straight 4"},
		}},
		{"Camp - Tents & Shelters", {
			{"p_tent02x"_J, "Small Tent"},
			{"p_tent04x"_J, "Medium Tent"},
			{"p_tent05bx"_J, "Large Tent"},
			{"p_tent07x"_J, "Covered Wagon Tent"},
			{"p_tent12x"_J, "Lean-To Shelter"},
			{"p_campfire01x"_J, "Basic Campfire"},
			{"p_campfire02x"_J, "Large Campfire"},
			{"p_campfirecombined01x"_J, "Campfire with Logs"},
			{"p_campfirekit01x"_J, "Campfire Cooking Pot"},
			{"s_inv_campfire01x"_J, "Small Fire Pit"},
		}},
		{"Camp - Furniture", {
			{"p_chair02x"_J, "Wooden Chair"},
			{"p_chair04x"_J, "Dining Chair"},
			{"p_chair05x"_J, "Rocking Chair"},
			{"p_chair06x"_J, "Camp Stool"},
			{"p_chair09x"_J, "Bench Seat"},
			{"p_chair12bx"_J, "Folding Chair"},
			{"p_chair13x"_J, "Office Chair"},
			{"p_bench01x"_J, "Wood Bench"},
			{"p_bench02x"_J, "Church Pew"},
			{"p_bench03x"_J, "Park Bench"},
			{"p_benchbroken01x"_J, "Rustic Bench"},
			{"p_table02x"_J, "Dining Table"},
			{"p_table06x"_J, "Work Table"},
			{"p_table07x"_J, "Round Table"},
			{"p_table08x"_J, "Small Side Table"},
			{"p_table09x"_J, "Card Table"},
			{"p_desk01x"_J, "Writing Desk"},
			{"p_dressingtable01x"_J, "Vanity Table"},
			{"p_bedindian01x"_J, "Indian Bedroll"},
			{"p_bedindian02x"_J, "Bedroll with Blanket"},
			{"p_bed01x"_J, "Single Bed"},
			{"p_bed02x"_J, "Double Bed"},
			{"p_bed03x"_J, "Cot"},
		}},
		{"Camp - Storage", {
			{"p_chest01x"_J, "Wooden Chest"},
			{"p_chest02x"_J, "Travel Chest"},
			{"p_chest03x"_J, "Storage Trunk"},
			{"p_chest04x"_J, "Lockbox"},
			{"p_chest05x"_J, "Money Chest"},
			{"p_crate01x"_J, "Wooden Crate"},
			{"p_crate02x"_J, "Small Crate"},
			{"p_crate03bx"_J, "Storage Crate"},
			{"p_crate04x"_J, "Ammo Crate"},
			{"p_crate05x"_J, "Large Crate"},
			{"p_barrel01x"_J, "Wooden Barrel"},
			{"p_barrel02x"_J, "Water Barrel"},
			{"p_barrel03x"_J, "Large Barrel"},
			{"p_barrel04bx"_J, "Wine Barrel"},
			{"p_barrelgroup01x"_J, "Barrel Cluster"},
			{"p_package01x"_J, "Wrapped Package"},
			{"p_package02x"_J, "Small Package"},
			{"p_bagpile01x"_J, "Bag Pile"},
			{"p_luggage01x"_J, "Luggage Set"},
			{"p_luggage02x"_J, "Travel Bags"},
		}},
		{"Camp - Lighting", {
			{"p_lantern01x"_J, "Hand Lantern"},
			{"p_lantern02x"_J, "Table Lantern"},
			{"p_lantern03x"_J, "Hanging Lantern"},
			{"p_lantern04x"_J, "Street Lamp Style"},
			{"p_lantern05x"_J, "Wall Mount Lantern"},
			{"p_lantern06x"_J, "Decorative Lantern"},
			{"p_candelabra01x"_J, "Candelabra"},
			{"p_candelabra02x"_J, "Small Candelabra"},
			{"p_candlestick01x"_J, "Single Candle"},
			{"p_candlestick02x"_J, "Tall Candlestick"},
			{"p_candlestick03x"_J, "Table Candle"},
			{"p_lampkerosene01x"_J, "Kerosene Lamp"},
			{"p_lampkerosene02x"_J, "Oil Lamp"},
			{"p_lamptable01x"_J, "Table Lamp"},
			{"p_lamptable02x"_J, "Reading Lamp"},
		}},
		{"Camp - Decoration", {
			{"p_rug01x"_J, "Small Rug"},
			{"p_rug02x"_J, "Large Rug"},
			{"p_rug03x"_J, "Persian Rug"},
			{"p_rug04x"_J, "Bear Skin Rug"},
			{"p_rug05x"_J, "Indian Rug"},
			{"p_blanket01x"_J, "Folded Blanket"},
			{"p_blanket02x"_J, "Wool Blanket"},
			{"p_pillow01x"_J, "Throw Pillow"},
			{"p_pelt01x"_J, "Deer Pelt"},
			{"p_pelt02x"_J, "Wolf Pelt"},
			{"p_pelt03x"_J, "Bear Pelt"},
			{"p_flowers01x"_J, "Flower Pot 1"},
			{"p_flowers02x"_J, "Flower Pot 2"},
			{"p_flowers03x"_J, "Wildflowers"},
			{"p_planter01x"_J, "Garden Planter"},
			{"p_planter02x"_J, "Window Box"},
			{"p_vase01x"_J, "Decorative Vase"},
			{"p_vase02x"_J, "Flower Vase"},
			{"p_clockwall01x"_J, "Wall Clock"},
			{"p_clockstand01x"_J, "Standing Clock"},
			{"p_mirror01x"_J, "Standing Mirror"},
			{"p_mirror02x"_J, "Wall Mirror"},
			{"p_painting01x"_J, "Painting 1"},
			{"p_painting02x"_J, "Painting 2"},
			{"p_painting03x"_J, "Landscape Painting"},
			{"p_frame01x"_J, "Picture Frame 1"},
			{"p_frame02x"_J, "Picture Frame 2"},
		}},
		{"Camp - Tools & Equipment", {
			{"p_anvil01x"_J, "Blacksmith Anvil"},
			{"p_grindstone01x"_J, "Grinding Wheel"},
			{"p_toolbox01x"_J, "Tool Box"},
			{"p_toolbench01x"_J, "Work Bench"},
			{"p_weaponrack01x"_J, "Weapon Rack"},
			{"p_saddlestand01x"_J, "Saddle Stand"},
			{"p_hitchingpost01x"_J, "Hitching Post 1"},
			{"p_hitchingpost02x"_J, "Hitching Post 2"},
			{"p_hitchingpost03x"_J, "Hitching Post 3"},
			{"p_wateringthrough01x"_J, "Water Trough"},
			{"p_feedbag01x"_J, "Feed Bag"},
			{"p_haybale01x"_J, "Hay Bale"},
			{"p_haybale02x"_J, "Hay Pile"},
			{"p_haypile01x"_J, "Loose Hay"},
			{"p_firewood01x"_J, "Firewood Stack"},
			{"p_firewood02x"_J, "Log Pile"},
			{"p_axe01x"_J, "Axe in Stump"},
			{"p_shovel01x"_J, "Shovel"},
			{"p_rake01x"_J, "Rake"},
			{"p_broom01x"_J, "Broom"},
		}},
		{"Camp - Cooking & Supplies", {
			{"p_pot01x"_J, "Cooking Pot"},
			{"p_pot02x"_J, "Large Pot"},
			{"p_kettle01x"_J, "Tea Kettle"},
			{"p_pan01x"_J, "Frying Pan"},
			{"p_coffeepot01x"_J, "Coffee Pot"},
			{"p_plate01x"_J, "Dinner Plate"},
			{"p_bowl01x"_J, "Wooden Bowl"},
			{"p_cup01x"_J, "Tin Cup"},
			{"p_mug01x"_J, "Coffee Mug"},
			{"p_bottle01x"_J, "Glass Bottle"},
			{"p_bottle02x"_J, "Wine Bottle"},
			{"p_bottle03x"_J, "Whiskey Bottle"},
			{"p_jug01x"_J, "Water Jug"},
			{"p_jug02x"_J, "Moonshine Jug"},
			{"p_basket01x"_J, "Wicker Basket"},
			{"p_basket02x"_J, "Egg Basket"},
			{"p_basket03x"_J, "Fruit Basket"},
			{"p_bucket01x"_J, "Wood Bucket"},
			{"p_bucket02x"_J, "Metal Bucket"},
			{"p_washbasin01x"_J, "Wash Basin"},
			{"p_washtub01x"_J, "Wash Tub"},
		}},
		{"Camp - Books & Music", {
			{"p_book01x"_J, "Closed Book"},
			{"p_book02x"_J, "Open Book"},
			{"p_bookstack01x"_J, "Stack of Books"},
			{"p_bookshelf01x"_J, "Small Bookshelf"},
			{"p_bookshelf02x"_J, "Large Bookshelf"},
			{"p_journal01x"_J, "Journal"},
			{"p_newspaper01x"_J, "Newspaper"},
			{"p_map01x"_J, "Wall Map"},
			{"p_piano01x"_J, "Upright Piano"},
			{"p_guitar01x"_J, "Acoustic Guitar"},
			{"p_banjo01x"_J, "Banjo"},
			{"p_violin01x"_J, "Violin"},
			{"p_harmonica01x"_J, "Harmonica"},
			{"p_grammophone01x"_J, "Gramophone"},
		}},
		{"Camp - Structures", {
			{"p_wall01x"_J, "Wood Wall Panel"},
			{"p_wall02x"_J, "Plank Wall"},
			{"p_wall03x"_J, "Log Wall"},
			{"p_door01x"_J, "Wooden Door"},
			{"p_door02x"_J, "Saloon Door"},
			{"p_window01x"_J, "Window Frame"},
			{"p_window02x"_J, "Large Window"},
			{"p_shutter01x"_J, "Window Shutter"},
			{"p_roof01x"_J, "Roof Section"},
			{"p_roof02x"_J, "Corrugated Roof"},
			{"p_stairs01x"_J, "Wooden Stairs"},
			{"p_stairs02x"_J, "Step Ladder"},
			{"p_ladder01x"_J, "Tall Ladder"},
			{"p_porch01x"_J, "Porch Section"},
			{"p_railing01x"_J, "Porch Railing"},
			{"p_column01x"_J, "Support Column"},
			{"p_beam01x"_J, "Wooden Beam"},
		}},
	};
}